### ISSUE TITLE
Acceptance Calculation 

### ISSUE THREAD

**Issue by LasDes** [miramliu/MuonTomography#1]
I have been reading and following the author Lesparre articles and also the one you have shared in this public repo. But I have some questions like how do you come to the calculation of the solid angle d𝜴 = A_pixel/ (D/2)^2 ?. And the value of the theoretic  acceptance calculation of 16 * 5^2 * 0.015 sr = 100 ?. Thank you very much If you do not mind how can I cite your work, it is pretty interesting regards muon geotomgraphy.

**Comment by miramliu** [comment]
Hi! Sorry for the slight delay and thanks so much for reaching out and I'm glad you've also found it pretty interesting! While this was just a quick rotation report that isn't published, here's our published paper with JAIS using this work that can be cited? http://journals.andromedapublisher.com/index.php/JAIS/article/view/280

Regarding solid angle, that's just using the simple definition of a solid angle covered by connecting the two edge corners of two pixels un-tilted. So knowing the width of the two pixels and the distance between them we just approximated the angle of coverage of connections between those two pixels assuming a straight line. 
Regarding theoretic acceptance, it may not have been clear but we used acceptance per angle as  detector area (16x16 of 25cm^2 pixels) * solid angle (at normal, .015sr) = (16 * 5)^2 * .015sr ~= 100 for the normal angle. Using those calculations we got an acceptance plot for our proposed detector per angle,  but noted we were getting different absolute acceptance values than they were, though the shape/form were highly similar regarding the total angular aperture. Hope this helps some!
Mira

**Comment by LasDes** [comment]
Thanks very much for the insights. Another question. Where does the term of the angular correction comes from? (Area * cos(θ) * cos(𝜙) )/r**2), this comes from the geometric diagram of figure 3 ? thanks

**Comment by miramliu** [comment]
Yes exactly. The solid angle between to parallel planes with no offset (Fig 2) covers a different pixel-area compared to planes that are still parallel but offset. We tried to show that geometrically in Figure 3! Another way of thinking of it is a cone bisected at different angles, and how that cross section will change as the angle changes. That's essentially what happens for area covered by solid angles if the pixels are offset. Hope this helps!

**Comment by LasDes** [comment]
Thanks a lot
